### ISSUE TITLE
Email Notification: Accessing dropdown variable returns label instead of value

### ISSUE THREAD

**Issue by acicovic** [BoldGrid/weforms#142]
Hello there,

I'm posting here to report [this thread](https://wordpress.org/support/topic/email-notification-accessing-dropdown-variable-returns-label-instead-of-value/) as a bug. Can anybody confirm this?

**Short description**

We have a dropdown containing contact names as label and their email address as the value for each dropdown item. When the user submits the form, an email notification should be sent to that email. However, WeForms tries to send the email to the dropdown’s selected **label** instead of value.

Thank you.

**Comment by avonville** [comment]
Hello @acicovic 

I am one of the developers for WeForms, and our December patch release which is coming out before the end of the year will include a fix to this issue. I have added new functionality to allow you to use a value: tag instead of field: tag for the address field in notifications. Please see below for more info:

 /**
     * Parse out the custom fields with options or values. Since the options are what is stored, options may need to be
     * used to find the value from the field settings.
     *
     * For example, let's say we have the following options:
     * DEPARTMENT / EMAIL
     * Support / support@example.com
     * Sales / sales@example.com
     *
     * Users need the ability to pass {field:department} and get "Support",
     * and {value:department} to get support@email.com
     
![image](https://user-images.githubusercontent.com/25781560/146606327-2fcf2699-58fd-41e8-8e06-003d48990f21.png)

This resolution will help any weforms user to be able to dynamically set the To, CC, etc. fields from the form input. This should also help reduce the need for any custom code needed or dependency on old code.

**Comment by acicovic** [comment]
@avonville, awesome stuff, thank you so much!
